export const CONSTS = {
    COMMAND_NONE: 0,

    COMMAND_UP: 1,
    COMMAND_DOWN: 2,
    COMMAND_LEFT: 10,
    COMMAND_RIGHT: 20,

    COMMAND_UP_LEFT: 11,
    COMMAND_UP_RIGHT: 21,
    COMMAND_DOWN_LEFT: 12,
    COMMAND_DOWN_RIGHT: 22
};